server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes non trouvées → index.html (React Router gère la suite)
    location / {
        try_files $uri $uri/ /index.html;
    }
}